//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiSIA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdSIAEntities : DbContext
    {
        public bdSIAEntities()
            : base("name=bdSIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAsignatura> tblAsignaturas { get; set; }
        public virtual DbSet<tblDetMat> tblDetMats { get; set; }
        public virtual DbSet<tblEstudiante> tblEstudiantes { get; set; }
        public virtual DbSet<tblFacultad> tblFacultads { get; set; }
        public virtual DbSet<tblJornada> tblJornadas { get; set; }
        public virtual DbSet<tblMatricula> tblMatriculas { get; set; }
        public virtual DbSet<tblPeriodo> tblPeriodoes { get; set; }
        public virtual DbSet<tblPrograma> tblProgramas { get; set; }
        public virtual DbSet<tblTipoDoc> tblTipoDocs { get; set; }
    }
}
