//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetMat
    {
        public int Codigo { get; set; }
        public string Fecha { get; set; }
        public int idMat { get; set; }
        public int idASI { get; set; }
    
        public virtual tblAsignatura tblAsignatura { get; set; }
        public virtual tblMatricula tblMatricula { get; set; }
    }
}
