//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEstudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEstudiante()
        {
            this.tblMatriculas = new HashSet<tblMatricula>();
        }
    
        public int Codigo { get; set; }
        public int NroDoc { get; set; }
        public int idTDOC { get; set; }
        public string Nombre { get; set; }
        public int idPRO { get; set; }
        public Nullable<int> idJOR { get; set; }
        public string Observac { get; set; }
        public bool Activo { get; set; }
    
        public virtual tblJornada tblJornada { get; set; }
        public virtual tblPrograma tblPrograma { get; set; }
        public virtual tblTipoDoc tblTipoDoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMatricula> tblMatriculas { get; set; }
    }
}
