//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMatricula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMatricula()
        {
            this.tblDetMats = new HashSet<tblDetMat>();
        }
    
        public int Codigo { get; set; }
        public string Fecha { get; set; }
        public int idPER { get; set; }
        public int idEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetMat> tblDetMats { get; set; }
        public virtual tblEstudiante tblEstudiante { get; set; }
        public virtual tblPeriodo tblPeriodo { get; set; }
    }
}
