//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiSIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrograma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPrograma()
        {
            this.tblAsignaturas = new HashSet<tblAsignatura>();
            this.tblEstudiantes = new HashSet<tblEstudiante>();
        }
    
        public int Codigo { get; set; }
        public int idFAC { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAsignatura> tblAsignaturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEstudiante> tblEstudiantes { get; set; }
        public virtual tblFacultad tblFacultad { get; set; }
    }
}
